// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Recruitment.Gorilla.API.Data;

#nullable disable

namespace Recruitment.Gorilla.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260709130322_RefineEvaluationFields")]
    partial class RefineEvaluationFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Recruitment.Gorilla.API.Models.CVFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.ToTable("CVFiles");
                });

            modelBuilder.Entity("Recruitment.Gorilla.API.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppliedRole")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CurrentTitle")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("GithubUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsReferred")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("OwnerUserId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PortfolioUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ReferenceEmail")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ReferenceEmployeeId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ReferenceName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("RoleAppliedOptionId")
                        .HasColumnType("int");

                    b.Property<string>("Skills")
                        .HasColumnType("longtext");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("RoleAppliedOptionId");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("Recruitment.Gorilla.API.Models.CandidateSkill", b =>
                {
                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int>("SkillOptionId")
                        .HasColumnType("int");

                    b.HasKey("CandidateId", "SkillOptionId");

                    b.HasIndex("SkillOptionId");

                    b.ToTable("CandidateSkills");
                });

            modelBuilder.Entity("Recruitment.Gorilla.API.Models.Interview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("StatusHistoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("StatusHistoryId");

                    b.ToTable("Interviews");
                });

            modelBuilder.Entity("Recruitment.Gorilla.API.Models.InterviewEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GeneralAssessment")
                        .HasColumnType("longtext");

                    b.Property<int>("InterviewId")
                        .HasColumnType("int");

                    b.Property<int>("InterviewerUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSubmitted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("OverallRating")
                        .HasColumnType("int");

                    b.Property<string>("Recommendation")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("RecommendationOther")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("InterviewerUserId");

                    b.HasIndex("InterviewId", "InterviewerUserId")
                        .IsUnique();

                    b.ToTable("InterviewEvaluations");
                });

            modelBuilder.Entity("Recruitment.Gorilla.API.Models.InterviewEvaluationItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("CriterionKey")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int>("InterviewEvaluationId")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InterviewEvaluationId", "CriterionKey")
                        .IsUnique();

                    b.ToTable("InterviewEvaluationItems");
                });

            modelBuilder.Entity("Recruitment.Gorilla.API.Models.InterviewInterviewer", b =>
                {
                    b.Property<int>("InterviewId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("InterviewId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("InterviewInterviewers");
                });

            modelBuilder.Entity("Recruitment.Gorilla.API.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Recruitment.Gorilla.API.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Recruitment.Gorilla.API.Models.RoleAppliedOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("PostedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Priority")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RoleAppliedOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Backend Engineer",
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Frontend Engineer",
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Full Stack Engineer",
                            SortOrder = 3,
                            UpdatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Machine Learning Engineer",
                            SortOrder = 4,
                            UpdatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "DevOps Engineer",
                            SortOrder = 5,
                            UpdatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "QA Engineer",
                            SortOrder = 6,
                            UpdatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Recruitment.Gorilla.API.Models.SkillOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SkillOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "C#",
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = ".NET",
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "React",
                            SortOrder = 3,
                            UpdatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "TypeScript",
                            SortOrder = 4,
                            UpdatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "SQL",
                            SortOrder = 5,
                            UpdatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Python",
                            SortOrder = 6,
                            UpdatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "AWS",
                            SortOrder = 7,
                            UpdatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Docker",
                            SortOrder = 8,
                            UpdatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Recruitment.Gorilla.API.Models.StatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("InterviewAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SubmissionUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("TaskDetails")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.ToTable("StatusHistories");
                });

            modelBuilder.Entity("Recruitment.Gorilla.API.Models.StatusOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsInitial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StatusOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsInitial = true,
                            Name = "Reject",
                            SortOrder = 14
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsInitial = false,
                            Name = "Call for Interview",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsInitial = false,
                            Name = "Interview Scheduled",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsInitial = true,
                            Name = "Not Available",
                            SortOrder = 12
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsInitial = false,
                            Name = "Technical Assessment",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsInitial = false,
                            Name = "Submission Receieved",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsInitial = false,
                            Name = "Code Review",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsInitial = false,
                            Name = "Interview Completed",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsInitial = false,
                            Name = "Recommended",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsInitial = false,
                            Name = "No Submission",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsInitial = false,
                            Name = "Not Recommended",
                            SortOrder = 13
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsInitial = true,
                            Name = "Discontinued",
                            SortOrder = 15
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsInitial = true,
                            Name = "Uploaded",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsInitial = false,
                            Name = "Ask for Assesment",
                            SortOrder = 2
                        });
                });

            modelBuilder.Entity("Recruitment.Gorilla.API.Models.StatusTransition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FromStatusOptionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("ToStatusOptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ToStatusOptionId");

                    b.HasIndex("FromStatusOptionId", "ToStatusOptionId")
                        .IsUnique();

                    b.ToTable("StatusTransitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FromStatusOptionId = 13,
                            IsActive = true,
                            SortOrder = 1,
                            ToStatusOptionId = 14
                        },
                        new
                        {
                            Id = 2,
                            FromStatusOptionId = 13,
                            IsActive = true,
                            SortOrder = 2,
                            ToStatusOptionId = 4
                        },
                        new
                        {
                            Id = 3,
                            FromStatusOptionId = 13,
                            IsActive = true,
                            SortOrder = 3,
                            ToStatusOptionId = 1
                        },
                        new
                        {
                            Id = 4,
                            FromStatusOptionId = 13,
                            IsActive = true,
                            SortOrder = 4,
                            ToStatusOptionId = 12
                        },
                        new
                        {
                            Id = 5,
                            FromStatusOptionId = 14,
                            IsActive = true,
                            SortOrder = 1,
                            ToStatusOptionId = 5
                        },
                        new
                        {
                            Id = 6,
                            FromStatusOptionId = 14,
                            IsActive = true,
                            SortOrder = 2,
                            ToStatusOptionId = 4
                        },
                        new
                        {
                            Id = 7,
                            FromStatusOptionId = 14,
                            IsActive = true,
                            SortOrder = 3,
                            ToStatusOptionId = 12
                        },
                        new
                        {
                            Id = 8,
                            FromStatusOptionId = 5,
                            IsActive = true,
                            SortOrder = 1,
                            ToStatusOptionId = 6
                        },
                        new
                        {
                            Id = 9,
                            FromStatusOptionId = 5,
                            IsActive = true,
                            SortOrder = 2,
                            ToStatusOptionId = 10
                        },
                        new
                        {
                            Id = 10,
                            FromStatusOptionId = 5,
                            IsActive = true,
                            SortOrder = 3,
                            ToStatusOptionId = 4
                        },
                        new
                        {
                            Id = 11,
                            FromStatusOptionId = 5,
                            IsActive = true,
                            SortOrder = 4,
                            ToStatusOptionId = 12
                        },
                        new
                        {
                            Id = 12,
                            FromStatusOptionId = 6,
                            IsActive = true,
                            SortOrder = 1,
                            ToStatusOptionId = 7
                        },
                        new
                        {
                            Id = 13,
                            FromStatusOptionId = 7,
                            IsActive = true,
                            SortOrder = 1,
                            ToStatusOptionId = 2
                        },
                        new
                        {
                            Id = 14,
                            FromStatusOptionId = 7,
                            IsActive = true,
                            SortOrder = 2,
                            ToStatusOptionId = 11
                        },
                        new
                        {
                            Id = 15,
                            FromStatusOptionId = 7,
                            IsActive = true,
                            SortOrder = 3,
                            ToStatusOptionId = 4
                        },
                        new
                        {
                            Id = 16,
                            FromStatusOptionId = 7,
                            IsActive = true,
                            SortOrder = 4,
                            ToStatusOptionId = 12
                        },
                        new
                        {
                            Id = 17,
                            FromStatusOptionId = 2,
                            IsActive = true,
                            SortOrder = 1,
                            ToStatusOptionId = 3
                        },
                        new
                        {
                            Id = 18,
                            FromStatusOptionId = 2,
                            IsActive = true,
                            SortOrder = 2,
                            ToStatusOptionId = 4
                        },
                        new
                        {
                            Id = 19,
                            FromStatusOptionId = 2,
                            IsActive = true,
                            SortOrder = 3,
                            ToStatusOptionId = 12
                        },
                        new
                        {
                            Id = 20,
                            FromStatusOptionId = 3,
                            IsActive = true,
                            SortOrder = 1,
                            ToStatusOptionId = 8
                        },
                        new
                        {
                            Id = 21,
                            FromStatusOptionId = 3,
                            IsActive = true,
                            SortOrder = 2,
                            ToStatusOptionId = 4
                        },
                        new
                        {
                            Id = 22,
                            FromStatusOptionId = 3,
                            IsActive = true,
                            SortOrder = 3,
                            ToStatusOptionId = 12
                        },
                        new
                        {
                            Id = 23,
                            FromStatusOptionId = 8,
                            IsActive = true,
                            SortOrder = 1,
                            ToStatusOptionId = 9
                        },
                        new
                        {
                            Id = 24,
                            FromStatusOptionId = 8,
                            IsActive = true,
                            SortOrder = 2,
                            ToStatusOptionId = 11
                        },
                        new
                        {
                            Id = 25,
                            FromStatusOptionId = 8,
                            IsActive = true,
                            SortOrder = 3,
                            ToStatusOptionId = 4
                        },
                        new
                        {
                            Id = 26,
                            FromStatusOptionId = 8,
                            IsActive = true,
                            SortOrder = 4,
                            ToStatusOptionId = 12
                        },
                        new
                        {
                            Id = 27,
                            FromStatusOptionId = 9,
                            IsActive = true,
                            SortOrder = 1,
                            ToStatusOptionId = 12
                        },
                        new
                        {
                            Id = 28,
                            FromStatusOptionId = 11,
                            IsActive = true,
                            SortOrder = 1,
                            ToStatusOptionId = 12
                        },
                        new
                        {
                            Id = 29,
                            FromStatusOptionId = 4,
                            IsActive = true,
                            SortOrder = 1,
                            ToStatusOptionId = 12
                        },
                        new
                        {
                            Id = 30,
                            FromStatusOptionId = 13,
                            IsActive = true,
                            SortOrder = 5,
                            ToStatusOptionId = 2
                        });
                });

            modelBuilder.Entity("Recruitment.Gorilla.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Recruitment.Gorilla.API.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Role")
                        .IsUnique();

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Recruitment.Gorilla.API.Models.CVFile", b =>
                {
                    b.HasOne("Recruitment.Gorilla.API.Models.Candidate", "Candidate")
                        .WithMany("CVFiles")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("Recruitment.Gorilla.API.Models.Candidate", b =>
                {
                    b.HasOne("Recruitment.Gorilla.API.Models.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Recruitment.Gorilla.API.Models.RoleAppliedOption", "RoleAppliedOption")
                        .WithMany()
                        .HasForeignKey("RoleAppliedOptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OwnerUser");

                    b.Navigation("RoleAppliedOption");
                });

            modelBuilder.Entity("Recruitment.Gorilla.API.Models.CandidateSkill", b =>
                {
                    b.HasOne("Recruitment.Gorilla.API.Models.Candidate", "Candidate")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recruitment.Gorilla.API.Models.SkillOption", "SkillOption")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("SkillOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("SkillOption");
                });

            modelBuilder.Entity("Recruitment.Gorilla.API.Models.Interview", b =>
                {
                    b.HasOne("Recruitment.Gorilla.API.Models.Candidate", "Candidate")
                        .WithMany("Interviews")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recruitment.Gorilla.API.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Recruitment.Gorilla.API.Models.StatusHistory", "StatusHistory")
                        .WithMany()
                        .HasForeignKey("StatusHistoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Candidate");

                    b.Navigation("CreatedByUser");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Recruitment.Gorilla.API.Models.InterviewEvaluation", b =>
                {
                    b.HasOne("Recruitment.Gorilla.API.Models.Interview", "Interview")
                        .WithMany("Evaluations")
                        .HasForeignKey("InterviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recruitment.Gorilla.API.Models.User", "InterviewerUser")
                        .WithMany()
                        .HasForeignKey("InterviewerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Interview");

                    b.Navigation("InterviewerUser");
                });

            modelBuilder.Entity("Recruitment.Gorilla.API.Models.InterviewEvaluationItem", b =>
                {
                    b.HasOne("Recruitment.Gorilla.API.Models.InterviewEvaluation", "InterviewEvaluation")
                        .WithMany("Items")
                        .HasForeignKey("InterviewEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterviewEvaluation");
                });

            modelBuilder.Entity("Recruitment.Gorilla.API.Models.InterviewInterviewer", b =>
                {
                    b.HasOne("Recruitment.Gorilla.API.Models.Interview", "Interview")
                        .WithMany("Interviewers")
                        .HasForeignKey("InterviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recruitment.Gorilla.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Interview");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Recruitment.Gorilla.API.Models.Notification", b =>
                {
                    b.HasOne("Recruitment.Gorilla.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Recruitment.Gorilla.API.Models.StatusHistory", b =>
                {
                    b.HasOne("Recruitment.Gorilla.API.Models.Candidate", "Candidate")
                        .WithMany("StatusHistories")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("Recruitment.Gorilla.API.Models.StatusTransition", b =>
                {
                    b.HasOne("Recruitment.Gorilla.API.Models.StatusOption", "FromStatusOption")
                        .WithMany()
                        .HasForeignKey("FromStatusOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Recruitment.Gorilla.API.Models.StatusOption", "ToStatusOption")
                        .WithMany()
                        .HasForeignKey("ToStatusOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromStatusOption");

                    b.Navigation("ToStatusOption");
                });

            modelBuilder.Entity("Recruitment.Gorilla.API.Models.UserRole", b =>
                {
                    b.HasOne("Recruitment.Gorilla.API.Models.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Recruitment.Gorilla.API.Models.Candidate", b =>
                {
                    b.Navigation("CVFiles");

                    b.Navigation("CandidateSkills");

                    b.Navigation("Interviews");

                    b.Navigation("StatusHistories");
                });

            modelBuilder.Entity("Recruitment.Gorilla.API.Models.Interview", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("Interviewers");
                });

            modelBuilder.Entity("Recruitment.Gorilla.API.Models.InterviewEvaluation", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Recruitment.Gorilla.API.Models.SkillOption", b =>
                {
                    b.Navigation("CandidateSkills");
                });

            modelBuilder.Entity("Recruitment.Gorilla.API.Models.User", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
